package org.moneymanagement.Mappers;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.moneymanagement.Entity.Category;
import org.moneymanagement.Payload.Request.CategoryRequest;
import org.moneymanagement.Payload.Response.CategoryResponse;

@Mapper(componentModel = "spring")
public interface CatogeryMapper {



    // Map CategoryRequest to Category Entity
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "createdAt", ignore = true) // DB handles creation timestamp
    @Mapping(target = "updatedAt", ignore = true) // DB handles update timestamp
    @Mapping(target = "profile.id", source = "profileId") // Map profileId from request to profile entity
    Category toCategory(CategoryRequest categoryRequest);

    // Map Category Entity to CategoryResponse
    @Mapping(source = "profile.id", target = "id") // optional if you want profileId in response
    @Mapping(source = "createdAt", target = "createdDate")
    @Mapping(source = "updatedAt", target = "updatedDate")
    CategoryResponse toCategoryResponse(Category category);

}
