version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: money-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    image:  money-management-app:latest
    container_name: money-app-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO:-update}
      BREVO_LOGIN: ${BREVO_LOGIN}
      BREVO_PASSWORD: ${BREVO_PASSWORD}
      BREVO_MAIL: ${BREVO_MAIL}


    ports:
      - "8009:8009"

volumes:
  mysql-data: